
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { get, set, del } from 'idb-keyval';

const SUPABASE_URL = "https://ylewpehqfgltbhpkaout.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZXdwZWhxZmdsdGJocGthb3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDkzMTcsImV4cCI6MjA2NTQyNTMxN30.ljNvNQSG0A2RsRkW8WXxADiOqVmZywD2GX318riotXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Configure client to persist sessions and auto refresh tokens even when
// the tab is not focused. This helps prevent hanging auth state when the
// user navigates away from the application.
// Use IndexedDB for auth token storage to avoid exposing tokens via localStorage
const authStorage = {
  getItem: (key: string) => get(key),
  setItem: (key: string, value: string) => set(key, value),
  removeItem: (key: string) => del(key),
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      multiTab: true,
      storage: authStorage,
    },
    realtime: {
      params: { eventsPerSecond: 10 },
    },
  }
);
